title: Stackbit Test Site
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg_img: images/header-bg.jpg
    has_nav: true
    has_social: true
    logo_img: images/logo.png
    tagline: >-
      I'm 3 parts Husband, 2 parts Father, 1 part Geek, 2 parts Christ-follower,
      6 parts Sarcasm, and 9 parts Sexy...wait...that's too many parts.
    title: Trae Blain
  palette: green
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
